# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
os:
  - linux
  - osx
r:
  - oldrel
  - release
  - devel
sudo: false
dist: trusty
cache: packages
warnings_are_errors: true

r_packages:
  - knitr
  - rmarkdown
  - devtools
  - testthat
  - covr

email:
  on_success: change
  on_failure: change

env:
  global:
    - _R_CHECK_FORCE_SUGGESTS_=false

after_success:
  - bash <(curl -s https://codecov.io/bash)
  - Rscript -e 'covr::codecov()'
